LLMClientConfig:
  model: "gpt-4o-mini"
  api_key: null
  system_prompt: "You are a helpful assistant."
  temperature: 0
  max_tokens: 4000
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0

